# Generated by Django 4.0.4 on 2022-05-22 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_vendor', '0002_vendorshop_delete_vendorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorshop',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_shop', to=settings.AUTH_USER_MODEL),
        ),
    ]
