# Generated by Django 3.2.9 on 2022-04-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
