# Generated by Django 3.2.9 on 2022-04-24 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_forum', '0002_auto_20220424_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='app_forum.forum'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
