# Generated by Django 3.2.9 on 2022-04-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forum', '0003_auto_20220424_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
