# Generated by Django 4.0.4 on 2022-05-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_product_shop_name_product_vendor_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='preview_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop_name',
        ),
    ]
