# Generated by Django 3.2.9 on 2022-04-25 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
