# Generated by Django 3.2.9 on 2022-04-20 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizstudentresult',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qstdres', to='app_dashboard.quiz'),
        ),
    ]
