# Generated by Django 3.2.9 on 2022-03-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='video',
            name='tviews',
            field=models.TextField(max_length=99999),
        ),
    ]
