# Generated by Django 3.2.9 on 2022-03-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220319_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='details',
            field=models.TextField(max_length=99999),
        ),
        migrations.AlterField(
            model_name='video',
            name='tviews',
            field=models.IntegerField(max_length=99999),
        ),
    ]
