# Generated by Django 3.2.9 on 2022-03-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220319_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vidurl',
            field=models.URLField(null=True),
        ),
    ]
