# Generated by Django 3.2.9 on 2022-04-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_video_vidurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='vidurl',
            field=models.URLField(default='https://www.youtube.com/embed/', null=True),
        ),
    ]
