# Generated by Django 3.2.9 on 2022-04-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.CharField(choices=[('', 'Please Select'), ('How To Articles', 'How To Articles'), ('List Articles', 'List Articles'), ('Round Up Articles', 'Round Up Articles'), ('Guide Articles', 'Guide Articles'), ('Comparison Articles', 'Comparison Articles'), ('How To Articles', 'How To Articles')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1),
        ),
    ]
