# Generated by Django 4.0.5 on 2022-06-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_car_rentcar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.ImageField(null=True, upload_to='car_images/'),
        ),
        migrations.AddField(
            model_name='rentcar',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rentcar',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
