# Generated by Django 4.0.5 on 2022-06-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_remove_car_color_car_images_rentcar_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcar',
            name='rent_date',
            field=models.DateField(null=True),
        ),
    ]
