# Generated by Django 4.0.4 on 2022-05-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_alter_profile_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('', 'Select Type'), ('Buyer', 'Buyer'), ('Seller', 'Seller')], max_length=20, null=True),
        ),
    ]
